//! Export report from Markdown: MD -> HTML (comrak + themed template), MD -> CSV (parse tables).
//!
//! The HTML export wraps the comrak-rendered body in a self-contained "Token Insight"
//! style document: dark sidebar TOC with scroll-spy, a blue gradient header banner with
//! report meta, summary stat cards derived from the Cluster Overview table, numbered
//! section cards, colored status badges, and percentage progress bars.

use anyhow::Result;
use base64::Engine;
use comrak::{markdown_to_html, ComrakOptions};

use crate::utils::lang::Lang;

/// Logo image embedded at compile time; encoded as data URI so HTML report is self-contained.
fn embedded_logo_data_uri() -> String {
    let bytes = include_bytes!("../../web/logo.png");
    format!(
        "data:image/png;base64,{}",
        base64::engine::general_purpose::STANDARD.encode(bytes)
    )
}

/// Escape text for safe embedding into HTML attributes / text nodes.
fn html_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            _ => out.push(c),
        }
    }
    out
}

/// Markdown structure extracted before rendering: title, header fields, overview
/// metrics (for the summary cards), headings (for the TOC) and the body to render.
struct ParsedReport {
    title: String,
    report_id: String,
    cluster: String,
    generated_at: String,
    overview: Vec<(String, String)>,
    headings: Vec<(u8, String)>,
    body_md: String,
}

/// Strip a `**Key**: value` / `**键**：值` field, trimming markdown/backticks.
fn field_value(line: &str, en: &str, zh: &str) -> Option<String> {
    let value = line.strip_prefix(en).or_else(|| line.strip_prefix(zh))?;
    Some(value.trim().trim_matches('`').trim().to_string())
}

fn is_metric_value_header(cells: &[&str]) -> bool {
    cells.len() >= 2
        && ((cells[0] == "Metric" && cells[1] == "Value")
            || (cells[0] == "指标" && cells[1] == "值"))
}

/// Parse the markdown report into its structural parts. The body keeps every table
/// (including the Cluster Overview one, which is also harvested for summary cards);
/// only the h1 title, the header fields and the footer lines are moved out.
fn parse_report(md: &str) -> ParsedReport {
    let mut title = String::new();
    let mut report_id = String::new();
    let mut cluster = String::new();
    let mut generated_at = String::new();
    let mut overview: Vec<(String, String)> = Vec::new();
    let mut headings: Vec<(u8, String)> = Vec::new();
    let mut body: Vec<&str> = Vec::new();
    let mut in_overview = false;
    let mut seen_subsection = false; // once an "###" appears, the Metric|Value table is no longer the cluster overview

    for line in md.lines() {
        let t = line.trim();
        // h1 title -> banner (skip in body)
        if title.is_empty() && t.starts_with("# ") && !t.starts_with("## ") {
            title = t[2..].trim().to_string();
            continue;
        }
        // Header fields -> banner meta
        if let Some(v) = field_value(t, "**Report ID**:", "**报告 ID**：") {
            report_id = v;
            continue;
        }
        if let Some(v) = field_value(t, "**Cluster**:", "**集群**：") {
            cluster = v;
            continue;
        }
        if let Some(v) = field_value(t, "**Generated At**:", "**生成时间**：") {
            generated_at = v;
            continue;
        }
        // Footer lines and horizontal rules are rendered by the themed template.
        if t.starts_with("*Report generated by") || t.starts_with("*报告由") || t == "---" {
            continue;
        }
        // Headings -> TOC
        if let Some(rest) = t.strip_prefix("### ") {
            seen_subsection = true;
            in_overview = false;
            headings.push((3, rest.trim().to_string()));
            body.push(line);
            continue;
        }
        if let Some(rest) = t.strip_prefix("## ") {
            in_overview = false;
            headings.push((2, rest.trim().to_string()));
            body.push(line);
            continue;
        }
        // Cluster Overview Metric|Value table (only the one before the first subsection)
        if !seen_subsection && t.starts_with('|') {
            let cells: Vec<&str> = t
                .split('|')
                .map(|c| c.trim())
                .filter(|c| !c.is_empty())
                .collect();
            if !in_overview && is_metric_value_header(&cells) {
                in_overview = true;
                body.push(line);
                continue;
            }
            if in_overview {
                if cells.len() >= 2 && !cells.iter().all(|c| c.chars().all(|ch| ch == '-')) {
                    overview.push((cells[0].to_string(), cells[1].to_string()));
                }
                body.push(line);
                continue;
            }
        }
        if !t.starts_with('|') {
            in_overview = false;
        }
        body.push(line);
    }

    ParsedReport {
        title,
        report_id,
        cluster,
        generated_at,
        overview,
        headings,
        body_md: body.join("\n") + "\n",
    }
}

/// Wrap each `<table>…</table>` in a horizontal-scroll container.
fn wrap_tables(content: &str) -> String {
    let mut out = String::with_capacity(content.len());
    let mut rest = content;
    loop {
        match rest.find("<table") {
            None => {
                out.push_str(rest);
                break;
            }
            Some(p) => {
                out.push_str(&rest[..p]);
                let after = &rest[p..];
                match after.find("</table>") {
                    Some(e) => {
                        let end = e + "</table>".len();
                        out.push_str("<div class=\"table-scroll\">");
                        out.push_str(&after[..end]);
                        out.push_str("</div>");
                        rest = &after[end..];
                    }
                    None => {
                        out.push_str(after);
                        break;
                    }
                }
            }
        }
    }
    out
}

/// Number `<h3>` headings (inject `id="sub-N"`) within a section's content.
fn inject_sub_ids(content: &str, sub: &mut usize) -> String {
    let mut out = String::with_capacity(content.len());
    let mut rest = content;
    loop {
        match rest.find("<h3>") {
            None => {
                out.push_str(rest);
                break;
            }
            Some(p) => {
                out.push_str(&rest[..p]);
                *sub += 1;
                out.push_str(&format!("<h3 id=\"sub-{}\">", *sub));
                rest = &rest[p + "<h3>".len()..];
            }
        }
    }
    out
}

/// Section content: wrap tables, assign h3 ids.
fn wrap_content(content: &str, sub: &mut usize) -> String {
    inject_sub_ids(&wrap_tables(content), sub)
}

/// Split the comrak-rendered body into numbered `<section>` cards (`id="sec-N"`),
/// one per `<h2>` block, and assign ids to `<h3>` sub-headings.
fn wrap_sections(body: &str) -> String {
    let mut out = String::with_capacity(body.len() + 512);
    let mut rest = body;
    let mut sub = 0usize;

    match rest.find("<h2") {
        None => {
            // No h2 at all: wrap everything in a single section.
            return format!(
                "<section class=\"section\">{}</section>",
                wrap_content(rest, &mut sub)
            );
        }
        Some(pos) => {
            let lead = &rest[..pos];
            if !lead.trim().is_empty() {
                out.push_str("<section class=\"section\">");
                out.push_str(&wrap_content(lead, &mut sub));
                out.push_str("</section>");
            }
            rest = &rest[pos..];
        }
    }

    let mut sec = 0usize;
    while !rest.is_empty() {
        // `rest` starts with "<h2"; locate the whole tag.
        let close_pos = rest.find("</h2>").expect("h2 tag must be closed");
        let h2_full_end = close_pos + "</h2>".len();
        let h2_tag = &rest[..h2_full_end];
        let open_end = h2_tag.find('>').expect("h2 open tag");
        sec += 1;
        out.push_str(&format!("<section class=\"section\" id=\"sec-{}\">", sec));
        out.push_str(&format!("<h2><span class=\"num\">{}.</span>", sec));
        let inner = &h2_tag[open_end + 1..]; // heading text + closing </h2>
        out.push_str(inner);

        let after_h2 = &rest[h2_full_end..];
        match after_h2.find("<h2") {
            Some(p) => {
                out.push_str(&wrap_content(&after_h2[..p], &mut sub));
                rest = &after_h2[p..];
            }
            None => {
                out.push_str(&wrap_content(after_h2, &mut sub));
                rest = "";
            }
        }
        out.push_str("</section>");
    }
    out
}

/// Build the dark sidebar TOC from the heading list. All `<h3>` sub-links are
/// shown so every section (including "Detailed Results") supports sub-navigation.
fn build_toc(headings: &[(u8, String)], logo_src: &str) -> String {
    let version = env!("CARGO_PKG_VERSION");
    let mut out = String::new();
    out.push_str("<nav class=\"toc\">");
    out.push_str(&format!(
        "<div class=\"toc-brand\"><img class=\"logo-img\" src=\"{0}\" alt=\"logo\"/><div class=\"meta\"><div class=\"name\">kcc</div><div class=\"ver\">v{1}</div></div></div>",
        logo_src, version
    ));
    let mut h2_idx = 0usize;
    let mut h3_idx = 0usize;
    let mut i = 0usize;
    while i < headings.len() {
        if headings[i].0 == 2 {
            h2_idx += 1;
            out.push_str(&format!(
                "<a href=\"#sec-{}\">{}</a>",
                h2_idx,
                html_escape(&headings[i].1)
            ));
            let mut j = i + 1;
            let mut subs: Vec<(usize, String)> = Vec::new();
            while j < headings.len() && headings[j].0 == 3 {
                h3_idx += 1;
                subs.push((h3_idx, headings[j].1.clone()));
                j += 1;
            }
            for (sid, text) in subs {
                out.push_str(&format!(
                    "<a class=\"sub\" href=\"#sub-{}\">{}</a>",
                    sid,
                    html_escape(&text)
                ));
            }
            i = j;
        } else {
            h3_idx += 1;
            i += 1;
        }
    }
    out.push_str("</nav>");
    out
}

/// Look up a localized overview row value (both language labels are matched).
fn overview_value<'a>(rows: &'a [(String, String)], zh: &str, en: &str) -> Option<&'a str> {
    rows.iter()
        .find(|(l, _)| l == zh || l == en)
        .map(|(_, v)| v.as_str())
}

fn short_label(lang: Lang, key: &str) -> &'static str {
    match (lang, key) {
        (Lang::Zh, "version") => "集群版本",
        (Lang::En, "version") => "Cluster Version",
        (Lang::Zh, "nodes") => "节点数",
        (Lang::En, "nodes") => "Nodes",
        (Lang::Zh, "pods") => "Pod 数",
        (Lang::En, "pods") => "Pods",
        (Lang::Zh, "ns") => "命名空间数",
        (Lang::En, "ns") => "Namespaces",
        (Lang::Zh, "age") => "集群年龄（天）",
        (Lang::En, "age") => "Cluster Age (days)",
        (Lang::Zh, "health") => "总体健康",
        (Lang::En, "health") => "Overall Health",
        _ => "",
    }
}

fn icon(kind: &str) -> &'static str {
    match kind {
        "version" => "<svg viewBox=\"0 0 24 24\"><path d=\"M12 1l-9 4v6c0 5.55 3.84 10.74 9 12 5.16-1.26 9-6.45 9-12V5l-9-4zm0 10.99h7c-.53 4.12-3.28 7.79-7 8.94V12H5V6.3l7-3.11v8.8z\"/></svg>",
        "nodes" => "<svg viewBox=\"0 0 24 24\"><path d=\"M4 3h16a1 1 0 0 1 1 1v6a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1zm0 10h16a1 1 0 0 1 1 1v6a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1v-6a1 1 0 0 1 1-1zM6 5v2h2V5H6zm0 10v2h2v-2H6z\"/></svg>",
        "pods" => "<svg viewBox=\"0 0 24 24\"><path d=\"M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5\"/></svg>",
        "ns" => "<svg viewBox=\"0 0 24 24\"><path d=\"M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z\"/></svg>",
        "age" => "<svg viewBox=\"0 0 24 24\"><path d=\"M11.99 2C6.47 2 2 6.48 2 12s4.47 10 9.99 10C17.52 22 22 17.52 22 12S17.52 2 11.99 2zM12 20c-4.42 0-8-3.58-8-8s3.58-8 8-8 8 3.58 8 8-3.58 8-8 8zm.5-13H11v6l5.25 3.15.75-1.23-4.5-2.67z\"/></svg>",
        "health" => "<svg viewBox=\"0 0 24 24\"><path d=\"M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z\"/></svg>",
        _ => "",
    }
}

fn card_html(tone: &str, color: &str, ico: &str, label: &str, value: &str, sub: &str) -> String {
    let value = html_escape(value);
    let label = html_escape(label);
    let sub_html = if sub.is_empty() {
        String::new()
    } else {
        format!(" <span class=\"sub\">{}</span>", html_escape(sub))
    };
    format!(
        "<div class=\"summary-card {0}\"><div class=\"ico\">{1}</div><div class=\"body\"><div class=\"num {2}\">{3}</div><div class=\"label\">{4}{5}</div></div></div>",
        tone, ico, color, value, label, sub_html
    )
}

/// Split an "Overall Health" value like `🟡 Good (Score: 82.4)` into
/// `(main_text, score)`.
fn split_health(value: &str) -> (String, String) {
    let mut main = value.trim().to_string();
    let mut score = String::new();
    let digits = |rest: &str| {
        rest.trim_start()
            .chars()
            .take_while(|c| c.is_ascii_digit() || *c == '.')
            .collect::<String>()
    };
    if let Some(p) = main.find("(Score:") {
        score = digits(&main[p + "(Score:".len()..]);
        main = main[..p].trim().to_string();
    } else if let Some(p) = main.find("（得分：") {
        score = digits(&main[p + "（得分：".len()..]);
        main = main[..p].trim().to_string();
    }
    (main, score)
}

fn health_tone(value: &str) -> (&'static str, &'static str) {
    if value.contains('🟢') {
        ("s-ok", "green")
    } else if value.contains('🟡') || value.contains('🟠') {
        ("s-warn", "orange")
    } else if value.contains('🔴') || value.contains('🚨') {
        ("s-crit", "red")
    } else {
        ("s-info", "blue")
    }
}

/// Summary stat cards from the Cluster Overview table (mirrors the reference style).
fn build_summary_cards(rows: &[(String, String)], lang: Lang) -> String {
    let mut cards: Vec<String> = Vec::new();
    if let Some(v) = overview_value(rows, "集群版本", "Cluster Version") {
        cards.push(card_html(
            "s-purple",
            "purple",
            icon("version"),
            short_label(lang, "version"),
            v,
            "",
        ));
    }
    if let Some(v) = overview_value(rows, "节点数", "Node Count") {
        let sub = match overview_value(rows, "就绪节点数", "Ready Nodes") {
            Some(ready) => match lang {
                Lang::Zh => format!("就绪 {} / {}", ready, v),
                Lang::En => format!("ready {} / {}", ready, v),
            },
            None => String::new(),
        };
        cards.push(card_html(
            "s-info",
            "blue",
            icon("nodes"),
            short_label(lang, "nodes"),
            v,
            &sub,
        ));
    }
    if let Some(v) = overview_value(rows, "Pod 数", "Pod Count") {
        cards.push(card_html(
            "s-orange",
            "orange",
            icon("pods"),
            short_label(lang, "pods"),
            v,
            "",
        ));
    }
    if let Some(v) = overview_value(rows, "命名空间数", "Namespace Count") {
        cards.push(card_html(
            "s-ok",
            "green",
            icon("ns"),
            short_label(lang, "ns"),
            v,
            "",
        ));
    }
    if let Some(v) = overview_value(rows, "集群年龄（天）", "Cluster Age (days)") {
        cards.push(card_html(
            "s-info",
            "blue",
            icon("age"),
            short_label(lang, "age"),
            v,
            "",
        ));
    }
    if let Some(v) = overview_value(rows, "总体健康状态", "Overall Health") {
        let (tone, color) = health_tone(v);
        let (main, score) = split_health(v);
        let sub = if score.is_empty() {
            String::new()
        } else {
            match lang {
                Lang::Zh => format!("得分 {}", score),
                Lang::En => format!("score {}", score),
            }
        };
        cards.push(card_html(
            tone,
            color,
            icon("health"),
            short_label(lang, "health"),
            &main,
            &sub,
        ));
    }
    if cards.is_empty() {
        return String::new();
    }
    format!("<div class=\"summary\">{}</div>", cards.join(""))
}

/// Blue gradient header banner with report meta.
fn build_header(p: &ParsedReport, lang: Lang) -> String {
    let (tag, id_k, cluster_k, gen_k, ver_k) = match lang {
        Lang::Zh => ("集群巡检", "报告 ID", "集群", "生成时间", "工具版本"),
        Lang::En => (
            "Cluster Check",
            "Report ID",
            "Cluster",
            "Generated At",
            "Version",
        ),
    };
    let title = if p.title.is_empty() {
        lang.html_title()
    } else {
        p.title.as_str()
    };
    let version = env!("CARGO_PKG_VERSION");
    format!(
        "<div class=\"header\"><div class=\"header-top\"><h1><span class=\"tag\">{0}</span>{1}</h1><span class=\"header-action\">HTML</span></div><div class=\"header-meta\"><div class=\"field\"><span class=\"k\">{2}:</span><span class=\"v\">{3}</span></div><div class=\"field\"><span class=\"k\">{4}:</span><span class=\"v\">{5}</span></div><div class=\"field\"><span class=\"k\">{6}:</span><span class=\"v\">{7}</span></div><div class=\"field\"><span class=\"k\">{8}:</span><span class=\"v\">v{9}</span></div></div></div>",
        tag,
        html_escape(title),
        id_k,
        html_escape(&p.report_id),
        cluster_k,
        html_escape(&p.cluster),
        gen_k,
        html_escape(&p.generated_at),
        ver_k,
        version
    )
}

/// Convert Markdown string to a full themed HTML document in the requested language.
pub fn md_to_html(md: &str, lang: Lang) -> Result<String> {
    let parsed = parse_report(md);

    let mut opts = ComrakOptions::default();
    opts.extension.table = true;
    let body = markdown_to_html(&parsed.body_md, &opts);
    let sections = wrap_sections(&body);

    let logo_src = embedded_logo_data_uri();
    let toc = build_toc(&parsed.headings, &logo_src);
    let header = build_header(&parsed, lang);
    let cards = build_summary_cards(&parsed.overview, lang);
    let footer = match lang {
        Lang::Zh => "报告由 kcc 生成",
        Lang::En => "Report generated by kcc",
    };

    let mut html = String::with_capacity(16_384);
    html.push_str("<!DOCTYPE html>\n<html lang=\"");
    html.push_str(lang.html_lang());
    html.push_str("\">\n<head>\n<meta charset=\"UTF-8\"/>\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\n<title>");
    html.push_str(lang.html_title());
    html.push_str("</title>\n<style>\n");
    html.push_str(THEME_CSS);
    html.push_str("\n</style>\n</head>\n<body>\n");
    html.push_str(&toc);
    html.push_str("<div class=\"container\">\n");
    html.push_str(&header);
    if !cards.is_empty() {
        html.push_str(&cards);
    }
    html.push_str(&sections);
    html.push_str(&format!("<div class=\"footer\">{}</div>\n</div>\n", footer));
    html.push_str(THEME_JS);
    html.push_str("</body>\n</html>");
    Ok(html)
}

const THEME_CSS: &str = r##"
:root {
  --c-primary: #1976d2;
  --c-primary-dark: #0d47a1;
  --c-primary-soft: #e8f1fc;
  --c-primary-soft-2: #f0f6ff;
  --c-text: #1f2937;
  --c-text-2: #4b5563;
  --c-muted: #6b7280;
  --c-bg: #f3f5f9;
  --c-card: #ffffff;
  --c-border: #d9dee7;
  --c-border-light: #eaedf3;
  --c-stripe: #fafbfd;
  --c-ok: #16a34a;
  --c-ok-soft: #e9f8ee;
  --c-warn: #d97706;
  --c-warn-soft: #fff4e0;
  --c-crit: #dc2626;
  --c-crit-soft: #fde8e8;
  --c-info: #1976d2;
  --c-info-soft: #e8f1fc;
  --c-neutral: #6b7280;
  --c-neutral-soft: #f1f2f4;
  --c-side-bg: #0f172a;
  --c-side-text: #cbd5e1;
  --c-side-muted: #64748b;
  --c-side-active: rgba(25, 118, 210, 0.18);
  --shadow-sm: 0 1px 2px rgba(15, 23, 42, 0.05);
  --shadow-md: 0 2px 8px rgba(15, 23, 42, 0.06), 0 1px 3px rgba(15, 23, 42, 0.05);
  --font-sans: -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Microsoft YaHei", "Helvetica Neue", Arial, sans-serif;
  --font-mono: ui-monospace, "SFMono-Regular", "Cascadia Code", "JetBrains Mono", Consolas, "Liberation Mono", "Menlo", "Courier New", monospace;
}
* { margin: 0; padding: 0; box-sizing: border-box; }
html { scroll-behavior: smooth; }
body { font-family: var(--font-sans); font-size: 14px; background: var(--c-bg); color: var(--c-text); line-height: 1.55; -webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale; }

/* ===== TOC: dark sidebar ===== */
.toc { position: fixed; left: 0; top: 0; bottom: 0; width: 220px; background: var(--c-side-bg); padding: 22px 0 16px; overflow-y: auto; z-index: 10; }
.toc-brand { padding: 0 22px 16px; border-bottom: 1px solid rgba(255, 255, 255, 0.08); margin-bottom: 12px; display: flex; align-items: center; gap: 10px; }
.toc-brand .logo-img { width: 28px; height: 28px; border-radius: 6px; flex-shrink: 0; object-fit: cover; background: #fff; }
.toc-brand .meta .name { font-size: 13px; font-weight: 600; color: #fff; letter-spacing: 0.2px; }
.toc-brand .meta .ver { font-size: 11px; color: var(--c-side-muted); font-family: var(--font-mono); margin-top: 1px; }
.toc a { display: flex; align-items: center; gap: 10px; padding: 8px 22px; color: var(--c-side-text); font-size: 13px; text-decoration: none; border-left: 3px solid transparent; transition: background 0.12s, color 0.12s, border-color 0.12s; }
.toc a:hover { background: rgba(255, 255, 255, 0.05); color: #fff; }
.toc a.active { background: var(--c-side-active); border-left-color: var(--c-primary); color: #fff; font-weight: 500; }
.toc a.sub { padding-left: 38px; font-size: 12px; color: var(--c-side-muted); }
.toc a.sub.active { color: #fff; }

/* ===== Layout ===== */
.container { max-width: 1280px; margin: 24px auto 24px 240px; padding: 0 28px; }

/* ===== Header banner ===== */
.header { background: linear-gradient(135deg, var(--c-primary) 0%, var(--c-primary-dark) 100%); color: #fff; padding: 22px 28px 18px; border-radius: 10px; margin-bottom: 18px; box-shadow: var(--shadow-md); position: relative; overflow: hidden; }
.header::after { content: ""; position: absolute; right: -40px; top: -40px; width: 240px; height: 240px; background: radial-gradient(circle, rgba(255, 255, 255, 0.10) 0%, transparent 70%); pointer-events: none; }
.header-top { display: flex; justify-content: space-between; align-items: center; margin-bottom: 14px; position: relative; z-index: 1; }
.header h1 { font-size: 20px; font-weight: 700; letter-spacing: -0.2px; }
.header h1 .tag { display: inline-block; background: rgba(255, 255, 255, 0.20); color: #fff; font-size: 11px; padding: 3px 9px; border-radius: 4px; margin-right: 8px; vertical-align: middle; font-weight: 600; }
.header-action { display: inline-flex; align-items: center; gap: 6px; background: rgba(255, 255, 255, 0.15); color: #fff; padding: 7px 14px; border-radius: 6px; font-size: 12px; border: 1px solid rgba(255, 255, 255, 0.25); cursor: default; }
.header-meta { display: flex; flex-wrap: wrap; gap: 22px 32px; position: relative; z-index: 1; }
.header-meta .field { font-size: 12.5px; }
.header-meta .field .k { color: rgba(255, 255, 255, 0.7); margin-right: 6px; }
.header-meta .field .v { color: #fff; font-weight: 500; font-family: var(--font-mono); }

/* ===== Summary cards ===== */
.summary { display: grid; grid-template-columns: repeat(6, 1fr); gap: 12px; margin-bottom: 18px; }
.summary-card { background: var(--c-card); border-radius: 8px; padding: 14px; box-shadow: var(--shadow-sm); border: 1px solid var(--c-border-light); display: flex; align-items: center; gap: 12px; }
.summary-card .ico { width: 38px; height: 38px; border-radius: 8px; display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
.summary-card .ico svg { width: 18px; height: 18px; fill: #fff; }
.summary-card.s-ok .ico { background: var(--c-ok); }
.summary-card.s-warn .ico { background: var(--c-warn); }
.summary-card.s-crit .ico { background: var(--c-crit); }
.summary-card.s-info .ico { background: var(--c-primary); }
.summary-card.s-purple .ico { background: #8b5cf6; }
.summary-card.s-orange .ico { background: #f59e0b; }
.summary-card .body { flex: 1; min-width: 0; }
.summary-card .num { font-size: 22px; font-weight: 700; line-height: 1.1; letter-spacing: -0.5px; word-break: break-all; }
.summary-card .label { font-size: 11px; color: var(--c-muted); margin-top: 4px; line-height: 1.3; }
.summary-card .label .sub { color: var(--c-muted); font-weight: 500; margin-left: 4px; }
.num.green { color: var(--c-ok); }
.num.orange { color: var(--c-warn); }
.num.red { color: var(--c-crit); }
.num.purple { color: #8b5cf6; }
.num.blue { color: var(--c-primary); }

/* ===== Section cards ===== */
.section { background: var(--c-card); border-radius: 10px; margin-bottom: 14px; box-shadow: var(--shadow-sm); border: 1px solid var(--c-border-light); overflow: hidden; }
.section[id] { scroll-margin-top: 16px; }
.section > *:not(h2) { padding-left: 24px; padding-right: 24px; }
.section > h2 { font-size: 15px; font-weight: 700; color: var(--c-primary-dark); margin: 0; padding: 12px 22px; background: var(--c-primary-soft-2); border-bottom: 1px solid var(--c-border-light); display: flex; align-items: center; letter-spacing: 0; }
.section > h2 .num { display: inline-block; color: var(--c-primary); font-weight: 700; margin-right: 8px; min-width: 18px; }
.section > *:first-child + * { padding-top: 18px; }
.section > *:last-child { padding-bottom: 20px; }
.section h3 { font-size: 12.5px; font-weight: 600; color: var(--c-text-2); margin: 18px 0 8px; }
.section h3:first-of-type { margin-top: 0; }
.section h4 { font-size: 12px; font-weight: 600; color: var(--c-text-2); margin: 16px 0 8px; }
.section p { font-size: 13px; color: var(--c-text-2); }
.section p:first-child { margin-top: 0; }
.section ul, .section ol { padding-left: 22px; font-size: 13px; color: var(--c-text-2); margin: 8px 0; }
.section a { color: var(--c-primary); }
.section strong { color: var(--c-text); }

/* ===== Tables ===== */
.table-scroll { overflow-x: auto; }
table { width: 100%; border-collapse: collapse; font-size: 13px; margin: 10px 0 4px; }
th { background: var(--c-primary-soft-2); text-align: left; padding: 9px 12px; font-weight: 600; font-size: 12px; color: var(--c-text-2); border-bottom: 1px solid var(--c-border-light); white-space: nowrap; }
td { padding: 8px 12px; border-bottom: 1px solid var(--c-border-light); word-break: break-all; vertical-align: top; font-size: 12.5px; line-height: 1.5; color: var(--c-text); }
tr:nth-child(even) td { background: var(--c-stripe); }
tr:hover td { background: var(--c-primary-soft); }
tr:last-child td { border-bottom: none; }

/* ===== Status badges ===== */
.badge { display: inline-block; padding: 2px 9px; border-radius: 10px; font-size: 11.5px; font-weight: 600; line-height: 1.5; }
.badge.ok { background: var(--c-ok-soft); color: var(--c-ok); }
.badge.warning { background: var(--c-warn-soft); color: var(--c-warn); }
.badge.critical { background: var(--c-crit-soft); color: var(--c-crit); }
.badge.info { background: var(--c-info-soft); color: var(--c-info); }
.badge.neutral { background: var(--c-neutral-soft); color: var(--c-neutral); }

/* ===== Progress bars ===== */
.progress-bar { background: var(--c-border-light); border-radius: 4px; height: 6px; overflow: hidden; display: inline-block; width: 80px; vertical-align: middle; margin-right: 8px; }
.progress-fill { height: 100%; transition: width 0.3s; }
.fill-ok { background: var(--c-ok); }
.fill-warn { background: var(--c-warn); }
.fill-crit { background: var(--c-crit); }

/* ===== Pre / code ===== */
pre { background: #0f172a; color: #cbd5e1; border: 1px solid #1e293b; padding: 14px 16px; border-radius: 6px; font-family: var(--font-mono); font-size: 12px; line-height: 1.6; overflow-x: auto; white-space: pre-wrap; word-break: break-all; max-height: 340px; overflow-y: auto; margin: 10px 0 4px; }
pre::-webkit-scrollbar { width: 8px; height: 8px; }
pre::-webkit-scrollbar-thumb { background: rgba(255, 255, 255, 0.12); border-radius: 4px; }
code { font-family: var(--font-mono); font-size: 0.92em; background: var(--c-primary-soft); padding: 1px 5px; border-radius: 4px; color: var(--c-primary-dark); }
pre code { background: none; padding: 0; color: inherit; }

/* ===== Misc ===== */
hr { border: none; border-top: 1px solid var(--c-border-light); margin: 14px 0; }
.footer { text-align: center; color: var(--c-muted); font-size: 12px; padding: 22px 0 12px; }
.section:target { animation: tgt 1.6s ease-out; }
@keyframes tgt { 0% { box-shadow: 0 0 0 3px var(--c-primary); } 100% { box-shadow: var(--shadow-sm); } }

/* ===== Mobile ===== */
@media (max-width: 900px) {
  .toc { position: relative; width: 100%; height: auto; padding: 14px 16px; }
  .toc-brand { padding-bottom: 10px; margin-bottom: 8px; }
  .toc a { display: inline-flex; padding: 4px 10px; border-left: none; border-radius: 4px; margin: 2px; font-size: 12px; }
  .toc a.sub { padding-left: 10px; }
  .container { margin-left: auto; margin-right: auto; padding: 16px; }
  .summary { grid-template-columns: repeat(2, 1fr); }
  .header-meta { gap: 10px 18px; }
  .header h1 { font-size: 17px; }
  .header-action { display: none; }
}

/* ===== Print ===== */
@media print {
  body { background: #fff; font-size: 10.5pt; color: #000; }
  .toc, .footer, .header-action { display: none !important; }
  .container { margin: 0; max-width: 100%; padding: 0; }
  .header { background: #1565c0 !important; color: #fff !important; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  .section, .summary-card { box-shadow: none; border: 1px solid #ccc; page-break-inside: avoid; }
  .summary { grid-template-columns: repeat(6, 1fr); }
  .summary-card { padding: 8px 6px; }
  pre { background: #f5f5f5 !important; color: #000 !important; max-height: none; overflow: visible; white-space: pre-wrap; }
  table { page-break-inside: auto; }
  tr { page-break-inside: avoid; page-break-after: auto; }
  a { color: inherit; text-decoration: none; }
}
"##;

const THEME_JS: &str = r##"<script>
(function () {
  // --- Status badges: turn status text cells into colored pills ---
  function norm(t) { return t.replace(/^[\s\u2705\u26a0\u274c\ud83d\udca5\ufe0f]+/, '').trim(); }
  function badgeCls(t) {
    var x = norm(t);
    if (/^(正常|良好|通过|是|已启用|已激活|运行中|运行正常|就绪|Yes|True|Pass|Good|Ok|OK|Enabled|Active|Running|Ready|UP|Enforcing|强制模式)$/i.test(x)) return 'ok';
    if (/^(警告|Warning|Warn|宽容模式|Permissive)$/i.test(x)) return 'warning';
    if (/^(严重|错误|已过期|Critical|Error|Failed|Expired)$/i.test(x)) return 'critical';
    if (/^(信息|未知|Info|Unknown)$/i.test(x)) return 'info';
    if (/^(否|无|未激活|已禁用|等待中|已退出|No|False|None|Disabled|Inactive|Pending|DOWN|down)$/i.test(x)) return 'neutral';
    return null;
  }
  document.querySelectorAll('td').forEach(function (td) {
    if (td.querySelector('a, code, pre')) return;
    var c = badgeCls(td.textContent);
    if (c) td.innerHTML = '<span class="badge ' + c + '">' + td.textContent.trim() + '</span>';
  });

  // --- Progress bars: usage columns become a bar + percentage ---
  document.querySelectorAll('table').forEach(function (t) {
    var idx = -1;
    t.querySelectorAll('th').forEach(function (h, i) {
      if (/used\s?%|已用百分比|使用率|usage/i.test(h.textContent)) idx = i;
    });
    if (idx < 0) return;
    t.querySelectorAll('tr').forEach(function (tr) {
      var td = tr.children[idx];
      if (!td) return;
      var m = td.textContent.trim().match(/^(\d+(?:\.\d+)?)%$/);
      if (!m) return;
      var p = parseFloat(m[1]);
      var cls = p >= 90 ? 'fill-crit' : (p >= 60 ? 'fill-warn' : 'fill-ok');
      td.innerHTML = '<span class="progress-bar"><span class="progress-fill ' + cls + '" style="width:' + Math.min(100, p) + '%"></span></span> ' + m[1] + '%';
    });
  });

  // --- Scroll-spy: highlight the TOC entry of the visible section ---
  var links = Array.prototype.slice.call(document.querySelectorAll('.toc a[href^="#"]'));
  var map = {};
  links.forEach(function (a) { var id = a.getAttribute('href').slice(1); if (document.getElementById(id)) map[id] = a; });
  if ('IntersectionObserver' in window) {
    var visible = new Set();
    var io = new IntersectionObserver(function (entries) {
      entries.forEach(function (e) { if (e.isIntersecting) visible.add(e.target.id); else visible.delete(e.target.id); });
      links.forEach(function (a) { a.classList.remove('active'); });
      var first = null;
      Object.keys(map).forEach(function (id) { if (visible.has(id) && !first) first = id; });
      if (first && map[first]) map[first].classList.add('active');
    }, { rootMargin: '-10% 0px -75% 0px', threshold: 0 });
    Object.keys(map).forEach(function (id) { io.observe(document.getElementById(id)); });
  }
})();
</script>
"##;

fn escape_csv(s: &str) -> String {
    if s.contains(',') || s.contains('"') || s.contains('\n') {
        format!("\"{}\"", s.replace('"', "\"\""))
    } else {
        s.to_string()
    }
}

/// Extract rule_id from a markdown link like [STO-409](url) or plain text.
fn extract_rule_id(cell: &str) -> String {
    let cell = cell.trim();
    if let Some(start) = cell.find('[') {
        if let Some(end) = cell[start..].find(']') {
            return cell[start + 1..start + end].to_string();
        }
    }
    cell.to_string()
}

/// Parse MD and convert to CSV: cluster_overview row + issue rows from per-resource tables.
pub fn md_to_csv(md: &str) -> Result<String> {
    let mut out = String::new();
    let lines: Vec<&str> = md.lines().collect();

    let mut cluster_name = String::new();
    let mut report_id = String::new();
    let mut overview: std::collections::HashMap<String, String> = std::collections::HashMap::new();
    let mut seen_cluster_overview = false;
    let mut in_overview_table = false;
    let mut overview_done = false;
    let mut current_section = String::new();
    let mut issue_rows: Vec<(String, String, String, String, String)> = Vec::new(); // section, resource, level, rule_id, short_title

    let mut i = 0;
    while i < lines.len() {
        let line = lines[i];
        if line.starts_with("**Cluster**:") || line.starts_with("**集群**：") {
            let prefix = if line.starts_with("**Cluster**:") {
                "**Cluster**:"
            } else {
                "**集群**："
            };
            cluster_name = line
                .trim_start_matches(prefix)
                .trim()
                .trim_matches(' ')
                .to_string();
        } else if line.starts_with("**Report ID**:") || line.starts_with("**报告 ID**：") {
            let prefix = if line.starts_with("**Report ID**:") {
                "**Report ID**:"
            } else {
                "**报告 ID**："
            };
            report_id = line
                .trim_start_matches(prefix)
                .trim()
                .trim_matches('`')
                .trim()
                .to_string();
        } else if (line.contains("Cluster Overview") || line.contains("集群概览"))
            && (line.starts_with("##") || line.contains("🖥️"))
        {
            seen_cluster_overview = true;
        } else if !overview_done
            && (seen_cluster_overview || in_overview_table)
            && line.starts_with('|')
        {
            let cells: Vec<&str> = line
                .split('|')
                .map(|c| c.trim())
                .filter(|c| !c.is_empty())
                .collect();
            let is_overview_header = cells.len() >= 2
                && ((cells[0] == "Metric" && cells[1] == "Value")
                    || (cells[0] == "指标" && cells[1] == "值"));
            if is_overview_header {
                in_overview_table = true;
                seen_cluster_overview = false;
            } else if in_overview_table
                && cells.len() >= 2
                && !cells[0].chars().all(|c| c == '-' || c == ' ')
            {
                // Normalize localized metric labels to canonical English keys.
                let canonical = match cells[0] {
                    "Cluster Version" | "集群版本" => "Cluster Version",
                    "Node Count" | "节点数" => "Node Count",
                    "Ready Nodes" | "就绪节点数" => "Ready Nodes",
                    "Pod Count" | "Pod 数" => "Pod Count",
                    "Namespace Count" | "命名空间数" => "Namespace Count",
                    "Cluster Age (days)" | "集群年龄（天）" => "Cluster Age (days)",
                    other => other,
                };
                overview.insert(canonical.to_string(), cells[1].to_string());
            }
        } else if in_overview_table && (!line.starts_with('|') || line.trim().is_empty()) {
            in_overview_table = false;
            overview_done = true;
        }
        if line.starts_with("## ")
            && !line.contains("Cluster Overview")
            && !line.contains("集群概览")
        {
            seen_cluster_overview = false;
        }

        if line.starts_with("### ") && !line.starts_with("#### ") {
            current_section = line.trim_start_matches("### ").trim().to_string();
        }

        let is_issue_table_header = (line.contains("Resource")
            && line.contains("Level")
            && line.contains("Issue Code")
            && line.contains("Short Title"))
            || (line.contains("资源")
                && line.contains("级别")
                && line.contains("问题代码")
                && line.contains("简要描述"));
        if line.starts_with('|') && is_issue_table_header {
            // Note: also matches the Chinese localized header (资源 | 级别 | 问题代码 | 简要描述).
            i += 1;
            if i < lines.len() && lines[i].contains("---") {
                i += 1;
            }
            while i < lines.len() && lines[i].starts_with('|') {
                let row = lines[i];
                let cells: Vec<&str> = row
                    .split('|')
                    .map(|c| c.trim())
                    .filter(|c| !c.is_empty())
                    .collect();
                if cells.len() >= 4 && !cells[0].chars().all(|c| c == '-') {
                    let resource = cells[0].trim_matches('`').to_string();
                    let level = cells[1].to_string();
                    let rule_id = extract_rule_id(cells.get(2).unwrap_or(&""));
                    let short_title = cells.get(3).unwrap_or(&"").to_string();
                    issue_rows.push((
                        current_section.clone(),
                        resource,
                        level,
                        rule_id,
                        short_title,
                    ));
                }
                i += 1;
            }
            continue;
        }
        i += 1;
    }

    out.push_str("section,cluster_name,report_id,cluster_version,node_count,ready_node_count,pod_count,namespace_count,cluster_age_days\n");
    let cv = overview.get("Cluster Version").cloned().unwrap_or_default();
    let nn = overview.get("Node Count").cloned().unwrap_or_default();
    let rn = overview.get("Ready Nodes").cloned().unwrap_or_default();
    let pc = overview.get("Pod Count").cloned().unwrap_or_default();
    let ns = overview.get("Namespace Count").cloned().unwrap_or_default();
    let age = overview
        .get("Cluster Age (days)")
        .cloned()
        .unwrap_or_default();
    out.push_str(&format!(
        "cluster_overview,{},{},{},{},{},{},{},{}\n",
        escape_csv(&cluster_name),
        escape_csv(&report_id),
        escape_csv(&cv),
        escape_csv(&nn),
        escape_csv(&rn),
        escape_csv(&pc),
        escape_csv(&ns),
        escape_csv(&age)
    ));

    out.push_str(
        "section,inspection_type,severity,category,description,resource,recommendation,rule_id\n",
    );
    for (section, resource, level, rule_id, short_title) in issue_rows {
        out.push_str(&format!(
            "issue,{0},{1},{2},{3},{4},{5},{6},{7}\n",
            escape_csv(&section),
            escape_csv(&section),
            escape_csv(&level),
            escape_csv(&section),
            escape_csv(&short_title),
            escape_csv(&resource),
            escape_csv(""),
            escape_csv(&rule_id),
        ));
    }

    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn md_to_csv_parses_cluster_overview() {
        let md = r#"# Report
**Report ID**: `test-id`
**Cluster**: my-cluster
**Generated At**: 2026-01-01 00:00:00 UTC
## Cluster Overview
| Metric | Value |
|--------|-------|
| Cluster Version | v1.33.7 |
| Node Count | 4 |
| Ready Nodes | 4 |
| Pod Count | 83 |
| Namespace Count | 13 |
| Cluster Age (days) | 11 |
### Pod
| Resource | Level | Issue Code | Short Title |
|----------|-------|------------|-------------|
| `ns/pod-1` | Critical | `103` | Restart count high |
"#;
        let csv = md_to_csv(md).unwrap();
        assert!(csv.contains("section,cluster_name,report_id,cluster_version,node_count,ready_node_count,pod_count,namespace_count,cluster_age_days"));
        assert!(
            csv.contains("cluster_overview"),
            "CSV must have cluster_overview row"
        );
        assert!(
            csv.contains("my-cluster") && csv.contains("test-id"),
            "cluster name and report id"
        );
        assert!(
            csv.contains("v1.33.7") && csv.contains(",4,4,83,13,11"),
            "overview metrics from Metric|Value table"
        );
        assert!(
            csv.contains("103") && csv.contains("Restart count high") && csv.contains("ns/pod-1"),
            "issue row from Resource|Level|Issue Code|Short Title table"
        );
    }

    #[test]
    fn md_to_html_renders_tables() {
        let md = r#"# Report
## Overview
| Metric | Value |
|--------|-------|
| Nodes | 4 |
"#;
        let html = md_to_html(md, Lang::Zh).unwrap();
        assert!(
            html.contains("<table>"),
            "HTML should contain <table> when extension.table is enabled"
        );
        assert!(html.contains("<tr>"));
        assert!(html.contains("<td>"));
        assert!(
            html.contains("data:image/png;base64,"),
            "HTML should embed logo as data URI for standalone report"
        );
        assert!(
            html.contains("<html lang=\"zh-CN\">"),
            "HTML lang attribute should follow report language"
        );
        assert!(
            html.contains("kubernetes 巡检报告"),
            "HTML title should be localized"
        );
    }

    #[test]
    fn md_to_html_uses_themed_layout() {
        let md = "# My Cluster\n\n**Cluster**: demo\n\n**Report ID**: `r1`\n\n**Generated At**: now\n\n## Overview\n\n| Metric | Value |\n|--------|-------|\n| Node Count | 3 |\n| Ready Nodes | 3 |\n| Pod Count | 12 |\n| Namespace Count | 5 |\n| Cluster Age (days) | 9 |\n| Overall Health | 🟢 Good (Score: 90.0) |\n\n### Details\n\n| Node | Status |\n|------|--------|\n| n1 | Good |\n\n## Issues\n\n### Pod\n\n| Resource | Level | Issue Code | Short Title |\n|----------|-------|------------|-------------|\n| `x/y` | Warning | `103` | Restart count high |\n";
        let html = md_to_html(md, Lang::Zh).unwrap();
        // Sidebar TOC + banner + section cards + summary cards
        assert!(html.contains("<nav class=\"toc\">"));
        assert!(html.contains("class=\"header\""));
        assert!(html.contains("class=\"section\""));
        assert!(html.contains("class=\"summary\""));
        assert!(html.contains("id=\"sec-1\""));
        assert!(html.contains("id=\"sec-2\""));
        assert!(html.contains("id=\"sub-1\""));
        // Banner meta extracted from header fields
        assert!(html.contains("demo"));
        assert!(html.contains("r1"));
        // Themed footer
        assert!(html.contains("报告由 kcc 生成"));
        // Badge / progress / scroll-spy JS is embedded
        assert!(html.contains("badgeCls"));
        assert!(html.contains("progress-fill"));
        assert!(html.contains("IntersectionObserver"));
        // Tables are wrapped in a scroll container
        assert!(html.contains("table-scroll"));
    }

    #[test]
    fn md_to_csv_parses_chinese_cluster_overview() {
        let md = r#"# 测试集群 Kubernetes 集群巡检报告
**报告 ID**：`test-id-zh`
**集群**：my-cluster
**生成时间**：2026-01-01 00:00:00 UTC
## 🖥️ 集群概览
| 指标 | 值 |
|--------|-------|
| 集群版本 | v1.33.7 |
| 节点数 | 4 |
| 就绪节点数 | 4 |
| Pod 数 | 83 |
| 命名空间数 | 13 |
| 集群年龄（天） | 11 |
### Pod
| 资源 | 级别 | 问题代码 | 简要描述 |
|----------|-------|------------|-------------|
| `ns/pod-1` | 严重 | `103` | 容器重启次数过高 |
"#;
        let csv = md_to_csv(md).unwrap();
        assert!(
            csv.contains("my-cluster") && csv.contains("test-id-zh"),
            "cluster name and report id from localized labels"
        );
        assert!(
            csv.contains("v1.33.7") && csv.contains(",4,4,83,13,11"),
            "overview metrics from localized Metric|Value table"
        );
        assert!(
            csv.contains("103") && csv.contains("容器重启次数过高") && csv.contains("ns/pod-1"),
            "issue row from localized issue table"
        );
    }
}
